; vsim modelsim.ini file
[Version]
INIVersion = "2025.3"

[Library]
others = $QUESTASIM_DIR/../modelsim.ini

; Design library compiled by qrun (-work xil_defaultlib)
xil_defaultlib = qrun.out/xil_defaultlib

; Task 2 XFFT and floating point
xbip_utils_v3_0_15 = /opt/tools/Questa/questa_sim_libs/xbip_utils_v3_0_15
axi_utils_v2_0_11 = /opt/tools/Questa/questa_sim_libs/axi_utils_v2_0_11
c_reg_fd_v12_0_11 = /opt/tools/Questa/questa_sim_libs/c_reg_fd_v12_0_11
xbip_dsp48_wrapper_v3_0_7 = /opt/tools/Questa/questa_sim_libs/xbip_dsp48_wrapper_v3_0_7
xbip_pipe_v3_0_11 = /opt/tools/Questa/questa_sim_libs/xbip_pipe_v3_0_11
c_addsub_v12_0_21 = /opt/tools/Questa/questa_sim_libs/c_addsub_v12_0_21
c_shift_ram_v12_0_20 = /opt/tools/Questa/questa_sim_libs/c_shift_ram_v12_0_20
mult_gen_v12_0_24 = /opt/tools/Questa/questa_sim_libs/mult_gen_v12_0_24
floating_point_v7_1_21 = /opt/tools/Questa/questa_sim_libs/floating_point_v7_1_21
cmpy_v6_0_27 = /opt/tools/Questa/questa_sim_libs/cmpy_v6_0_27
xfft_v9_1_15 = /opt/tools/Questa/questa_sim_libs/xfft_v9_1_15

; Task 8 MicroBlaze system
microblaze_v11_0_16 = /opt/tools/Questa/questa_sim_libs/microblaze_v11_0_16
lmb_v10_v3_0_16 = /opt/tools/Questa/questa_sim_libs/lmb_v10_v3_0_16
lmb_bram_if_cntlr_v4_0_27 = /opt/tools/Questa/questa_sim_libs/lmb_bram_if_cntlr_v4_0_27
axi_datamover_v5_1_37 = /opt/tools/Questa/questa_sim_libs/axi_datamover_v5_1_37
axi_sg_v4_1_21 = /opt/tools/Questa/questa_sim_libs/axi_sg_v4_1_21
axi_dma_v7_1_37 = /opt/tools/Questa/questa_sim_libs/axi_dma_v7_1_37
axis_infrastructure_v1_1_1 = /opt/tools/Questa/questa_sim_libs/axis_infrastructure_v1_1_1
axis_data_fifo_v2_0_17 = /opt/tools/Questa/questa_sim_libs/axis_data_fifo_v2_0_17

; design_1 block design
blk_mem_gen_v8_4_12 = /opt/tools/Questa/questa_sim_libs/blk_mem_gen_v8_4_12
proc_sys_reset_v5_0_17 = /opt/tools/Questa/questa_sim_libs/proc_sys_reset_v5_0_17
axi_bram_ctrl_v4_1_13 = /opt/tools/Questa/questa_sim_libs/axi_bram_ctrl_v4_1_13
smartconnect_v1_0 = /opt/tools/Questa/questa_sim_libs/smartconnect_v1_0
axi_infrastructure_v1_1_0 = /opt/tools/Questa/questa_sim_libs/axi_infrastructure_v1_1_0
axi_register_slice_v2_1_36 = /opt/tools/Questa/questa_sim_libs/axi_register_slice_v2_1_36
axi_vip_v1_1_22 = /opt/tools/Questa/questa_sim_libs/axi_vip_v1_1_22
zynq_ultra_ps_e_vip_v1_0_22 = /opt/tools/Questa/questa_sim_libs/zynq_ultra_ps_e_vip_v1_0_22
xlconstant_v1_1_10 = /opt/tools/Questa/questa_sim_libs/xlconstant_v1_1_10

; Primitives and VIP
xilinx_vip = /opt/tools/Questa/questa_sim_libs/xilinx_vip
xpm = /opt/tools/Questa/questa_sim_libs/xpm
unisims_ver = /opt/tools/Questa/questa_sim_libs/unisims_ver
unimacro_ver = /opt/tools/Questa/questa_sim_libs/unimacro_ver
secureip = /opt/tools/Questa/questa_sim_libs/secureip
unisim = /opt/tools/Questa/questa_sim_libs/unisim
