//
// File: top_fir_vseq.svh
//
// Custom FIR filter bank virtual sequence.
// Extends top_example_vseq (the autogenerated base) and runs five
// test vectors (TV0–TV41)
class top_fir_vseq extends top_example_vseq;
    `uvm_object_utils(top_fir_vseq)
    function new
    (
        string name = "top_fir_vseq"
    );
        super.new(name);
    endfunction

    // -----------------------------------------------------------------------
    // Q1.15 conversion — matches tb_pkg::real_to_q15
    // -----------------------------------------------------------------------
    function automatic logic signed [15:0] real_to_q15(input real val);
        real clamped;
        clamped = (val >  0.999969482421875) ?  0.999969482421875 :
                  (val < -1.0)               ? -1.0               : val;
        return 16'(int'(clamped * 32768.0));
    endfunction

    // -----------------------------------------------------------------------
    // Pack 16-bit Q1.15 value into bytes at word_idx (upper 16 bits = 0)
    // -----------------------------------------------------------------------
    function automatic void pack_val(
        ref   byte unsigned       payload [],
        input int                 word_idx,
        input logic signed [15:0] val
    );
        payload[word_idx*4 + 0] = byte'(val[7:0]);
        payload[word_idx*4 + 1] = byte'(val[15:8]);
        payload[word_idx*4 + 2] = 8'h00;
        payload[word_idx*4 + 3] = 8'h00;
    endfunction

    // -----------------------------------------------------------------------
    // Pack header {N[31:24], T[23:16], S[15:0]} at word 0
    // -----------------------------------------------------------------------
    function automatic void pack_header(
        ref byte unsigned payload [],
        input int N, T, S
    );
        payload[0] = byte'(S);
        payload[1] = byte'(S >> 8);
        payload[2] = byte'(T);
        payload[3] = byte'(N);
    endfunction

    extern task body;

endclass: top_fir_vseq

task top_fir_vseq::body;
    aaxi_stream_all_byte_seq aaxi4_stream_master_0_seq_0;
    aaxi_stream_all_byte_seq aaxi4_stream_master_0_seq_1;
    aaxi_stream_all_byte_seq aaxi4_stream_master_0_seq_2;
    aaxi_stream_all_byte_seq aaxi4_stream_master_0_seq_3;
    aaxi_stream_all_byte_seq aaxi4_stream_master_0_seq_4;

    // =========================================================================
    // TV0: 1ch, 4-tap, unit impulse  (N=1, T=4, S=8)
    // Packet layout (each word = 4 bytes, little-endian on TDATA):
    //   Word 0     : header {N[31:24], T[23:16], S[15:0]} = 0x01_04_0008
    //   Words 1-4  : coefficients (Q1.15 in s_data[15:0], upper 16b = 0)
    //                4-tap moving average: [0.25, 0.25, 0.25, 0.25] = [0x2000 x4]
    //   Words 5-12 : samples (Q1.15 in s_data[15:0], upper 16b = 0)
    //                unit impulse: [0x7FFF, 0, 0, 0, 0, 0, 0, 0]
    // Total = 13 words x 4 bytes = 52 bytes
    // =========================================================================
    aaxi4_stream_master_0_seq_0 = aaxi_stream_all_byte_seq::type_id::create("aaxi_stream_all_byte_seq");

    // Build payload as raw bytes (little-endian per word: byte[0]=TDATA[7:0])
    aaxi4_stream_master_0_seq_0.payload = new[52];
    // Word 0: header N=1, T=4, S=8 => 0x01040008
    aaxi4_stream_master_0_seq_0.payload[ 0] = 8'h08; // S[7:0]
    aaxi4_stream_master_0_seq_0.payload[ 1] = 8'h00; // S[15:8]
    aaxi4_stream_master_0_seq_0.payload[ 2] = 8'h04; // T[7:0]
    aaxi4_stream_master_0_seq_0.payload[ 3] = 8'h01; // N[7:0]
    // Word 1: coeff[0][0] = 0x2000 (0.25 in Q1.15)
    aaxi4_stream_master_0_seq_0.payload[ 4] = 8'h00;
    aaxi4_stream_master_0_seq_0.payload[ 5] = 8'h20;
    aaxi4_stream_master_0_seq_0.payload[ 6] = 8'h00;
    aaxi4_stream_master_0_seq_0.payload[ 7] = 8'h00;
    // Word 2: coeff[0][1] = 0x2000 (0.25 in Q1.15)
    aaxi4_stream_master_0_seq_0.payload[ 8] = 8'h00;
    aaxi4_stream_master_0_seq_0.payload[ 9] = 8'h20;
    aaxi4_stream_master_0_seq_0.payload[10] = 8'h00;
    aaxi4_stream_master_0_seq_0.payload[11] = 8'h00;
    // Word 3: coeff[0][2] = 0x2000 (0.25 in Q1.15)
    aaxi4_stream_master_0_seq_0.payload[12] = 8'h00;
    aaxi4_stream_master_0_seq_0.payload[13] = 8'h20;
    aaxi4_stream_master_0_seq_0.payload[14] = 8'h00;
    aaxi4_stream_master_0_seq_0.payload[15] = 8'h00;
    // Word 4: coeff[0][3] = 0x2000 (0.25 in Q1.15)
    aaxi4_stream_master_0_seq_0.payload[16] = 8'h00;
    aaxi4_stream_master_0_seq_0.payload[17] = 8'h20;
    aaxi4_stream_master_0_seq_0.payload[18] = 8'h00;
    aaxi4_stream_master_0_seq_0.payload[19] = 8'h00;
    // Word 5: sample[0][0] = 0x7FFF (unit impulse, ~1.0 in Q1.15)
    aaxi4_stream_master_0_seq_0.payload[20] = 8'hFF;
    aaxi4_stream_master_0_seq_0.payload[21] = 8'h7F;
    aaxi4_stream_master_0_seq_0.payload[22] = 8'h00;
    aaxi4_stream_master_0_seq_0.payload[23] = 8'h00;
    // Words 6-12: samples[0][1..7] = 0
    aaxi4_stream_master_0_seq_0.payload[24] = 8'h00;
    aaxi4_stream_master_0_seq_0.payload[25] = 8'h00;
    aaxi4_stream_master_0_seq_0.payload[26] = 8'h00;
    aaxi4_stream_master_0_seq_0.payload[27] = 8'h00;
    aaxi4_stream_master_0_seq_0.payload[28] = 8'h00;
    aaxi4_stream_master_0_seq_0.payload[29] = 8'h00;
    aaxi4_stream_master_0_seq_0.payload[30] = 8'h00;
    aaxi4_stream_master_0_seq_0.payload[31] = 8'h00;
    aaxi4_stream_master_0_seq_0.payload[32] = 8'h00;
    aaxi4_stream_master_0_seq_0.payload[33] = 8'h00;
    aaxi4_stream_master_0_seq_0.payload[34] = 8'h00;
    aaxi4_stream_master_0_seq_0.payload[35] = 8'h00;
    aaxi4_stream_master_0_seq_0.payload[36] = 8'h00;
    aaxi4_stream_master_0_seq_0.payload[37] = 8'h00;
    aaxi4_stream_master_0_seq_0.payload[38] = 8'h00;
    aaxi4_stream_master_0_seq_0.payload[39] = 8'h00;
    aaxi4_stream_master_0_seq_0.payload[40] = 8'h00;
    aaxi4_stream_master_0_seq_0.payload[41] = 8'h00;
    aaxi4_stream_master_0_seq_0.payload[42] = 8'h00;
    aaxi4_stream_master_0_seq_0.payload[43] = 8'h00;
    aaxi4_stream_master_0_seq_0.payload[44] = 8'h00;
    aaxi4_stream_master_0_seq_0.payload[45] = 8'h00;
    aaxi4_stream_master_0_seq_0.payload[46] = 8'h00;
    aaxi4_stream_master_0_seq_0.payload[47] = 8'h00;
    aaxi4_stream_master_0_seq_0.payload[48] = 8'h00;
    aaxi4_stream_master_0_seq_0.payload[49] = 8'h00;
    aaxi4_stream_master_0_seq_0.payload[50] = 8'h00;
    aaxi4_stream_master_0_seq_0.payload[51] = 8'h00;

    aaxi4_stream_master_0_seq_0.byte_type = new[52];
    foreach (aaxi4_stream_master_0_seq_0.byte_type[i])
        aaxi4_stream_master_0_seq_0.byte_type[i] = AAXISTREAM_DATA_BYTE;

    aaxi4_stream_master_0_seq_0.start(aaxi4_stream_master_0);
    // Wait for DUT to flush all TV0 output before sending next packet header.
    // seq.start() returns when the last byte is sent, but the DUT pipeline
    // is still computing — the next header would reset the packetizer mid-stream.
    #10us;

    // =========================================================================
    // TV1: 2ch, 8-tap, sinusoidal input  (N=2, T=8, S=16)
    // Word layout: W0=header, W1-8=ch0 coeffs, W9-16=ch1 coeffs,
    //              W17-32=ch0 samples, W33-48=ch1 samples  →  49 words = 196 B
    // =========================================================================
    aaxi4_stream_master_0_seq_1 = aaxi_stream_all_byte_seq::type_id::create("tv1_seq");
    aaxi4_stream_master_0_seq_1.payload   = new[196];
    aaxi4_stream_master_0_seq_1.byte_type = new[196];
    foreach (aaxi4_stream_master_0_seq_1.byte_type[i])
        aaxi4_stream_master_0_seq_1.byte_type[i] = AAXISTREAM_DATA_BYTE;

    // Header: N=2, T=8, S=16 => 0x02_08_0010
    pack_header(aaxi4_stream_master_0_seq_1.payload, 2, 8, 16);

    // ch0 coefficients: Hann-windowed low-pass (fc=0.1)
    pack_val(aaxi4_stream_master_0_seq_1.payload,  1, real_to_q15( 0.0045));
    pack_val(aaxi4_stream_master_0_seq_1.payload,  2, real_to_q15( 0.0428));
    pack_val(aaxi4_stream_master_0_seq_1.payload,  3, real_to_q15( 0.1472));
    pack_val(aaxi4_stream_master_0_seq_1.payload,  4, real_to_q15( 0.2983));
    pack_val(aaxi4_stream_master_0_seq_1.payload,  5, real_to_q15( 0.2983));
    pack_val(aaxi4_stream_master_0_seq_1.payload,  6, real_to_q15( 0.1472));
    pack_val(aaxi4_stream_master_0_seq_1.payload,  7, real_to_q15( 0.0428));
    pack_val(aaxi4_stream_master_0_seq_1.payload,  8, real_to_q15( 0.0045));

    // ch1 coefficients: identity / delta filter
    pack_val(aaxi4_stream_master_0_seq_1.payload,  9, real_to_q15(1.0));
    for (int k = 1; k < 8; k++)
        pack_val(aaxi4_stream_master_0_seq_1.payload, 9+k, real_to_q15(0.0));

    // ch0 samples: 0.8 * sin(2π * 0.05 * n),  n=0..15
    for (int n = 0; n < 16; n++)
        pack_val(aaxi4_stream_master_0_seq_1.payload, 17+n,
                 real_to_q15(0.8 * $sin(2.0 * 3.14159265358979 * 0.05 * n)));

    // ch1 samples: 0.5 * cos(2π * 0.1 * n),  n=0..15
    for (int n = 0; n < 16; n++)
        pack_val(aaxi4_stream_master_0_seq_1.payload, 33+n,
                 real_to_q15(0.5 * $cos(2.0 * 3.14159265358979 * 0.1  * n)));

    aaxi4_stream_master_0_seq_1.start(aaxi4_stream_master_0);
    #10us; // Wait for DUT to flush TV1 output

    // =========================================================================
    // TV2: 4ch, 16-tap, saturation stress  (N=4, T=16, S=8)
    // Word layout: W0=header, W1-64=all-ch coeffs, W65-96=all-ch samples
    //              →  97 words = 388 B
    // =========================================================================
    aaxi4_stream_master_0_seq_2 = aaxi_stream_all_byte_seq::type_id::create("tv2_seq");
    aaxi4_stream_master_0_seq_2.payload   = new[388];
    aaxi4_stream_master_0_seq_2.byte_type = new[388];
    foreach (aaxi4_stream_master_0_seq_2.byte_type[i])
        aaxi4_stream_master_0_seq_2.byte_type[i] = AAXISTREAM_DATA_BYTE;

    // Header: N=4, T=16, S=8 => 0x04_10_0008
    pack_header(aaxi4_stream_master_0_seq_2.payload, 4, 16, 8);

    // All coefficients: 0.5 (channel-major order: ch0 taps, ch1 taps, ...)
    for (int c = 0; c < 4; c++)
        for (int k = 0; k < 16; k++)
            pack_val(aaxi4_stream_master_0_seq_2.payload, 1 + c*16 + k,
                     real_to_q15(0.5));

    // All samples: 0.9999 (channel-major: ch0 samples, ch1 samples, ...)
    for (int c = 0; c < 4; c++)
        for (int n = 0; n < 8; n++)
            pack_val(aaxi4_stream_master_0_seq_2.payload, 65 + c*8 + n,
                     real_to_q15(0.9999));

    aaxi4_stream_master_0_seq_2.start(aaxi4_stream_master_0);
    #10us; // Wait for DUT to flush TV2 output

    // =========================================================================
    // TV3: 1ch, 4-tap, max samples  (N=1, T=4, S=64)
    // Word layout: W0=header, W1-4=coeffs, W5-68=samples  →  69 words = 276 B
    // =========================================================================
    aaxi4_stream_master_0_seq_3 = aaxi_stream_all_byte_seq::type_id::create("tv3_seq");
    aaxi4_stream_master_0_seq_3.payload   = new[276];
    aaxi4_stream_master_0_seq_3.byte_type = new[276];
    foreach (aaxi4_stream_master_0_seq_3.byte_type[i])
        aaxi4_stream_master_0_seq_3.byte_type[i] = AAXISTREAM_DATA_BYTE;

    // Header: N=1, T=4, S=64 => 0x01_04_0040
    pack_header(aaxi4_stream_master_0_seq_3.payload, 1, 4, 64);

    // Differentiator coefficients: [0.5, -0.5, 0.0, 0.0]
    pack_val(aaxi4_stream_master_0_seq_3.payload, 1, real_to_q15( 0.5));
    pack_val(aaxi4_stream_master_0_seq_3.payload, 2, real_to_q15(-0.5));
    pack_val(aaxi4_stream_master_0_seq_3.payload, 3, real_to_q15( 0.0));
    pack_val(aaxi4_stream_master_0_seq_3.payload, 4, real_to_q15( 0.0));

    // Ramp samples: (n % 32) / 32.0 * 0.9,  n=0..63
    for (int n = 0; n < 64; n++)
        pack_val(aaxi4_stream_master_0_seq_3.payload, 5+n,
                 real_to_q15((real'(n % 32) / 32.0) * 0.9));

    aaxi4_stream_master_0_seq_3.start(aaxi4_stream_master_0);
    #10us; // Wait for DUT to flush TV3 output

    // =========================================================================
    // TV4: 3ch, 12-tap, alternating coefficients  (N=3, T=12, S=20)
    // Word layout: W0=header, W1-36=all-ch coeffs, W37-96=all-ch samples
    //              →  97 words = 388 B
    // =========================================================================
    aaxi4_stream_master_0_seq_4 = aaxi_stream_all_byte_seq::type_id::create("tv4_seq");
    aaxi4_stream_master_0_seq_4.payload   = new[388];
    aaxi4_stream_master_0_seq_4.byte_type = new[388];
    foreach (aaxi4_stream_master_0_seq_4.byte_type[i])
        aaxi4_stream_master_0_seq_4.byte_type[i] = AAXISTREAM_DATA_BYTE;

    // Header: N=3, T=12, S=20 => 0x03_0C_0014
    pack_header(aaxi4_stream_master_0_seq_4.payload, 3, 12, 20);

    // Alternating-sign coefficients: +0.083 (even tap), -0.083 (odd tap)
    for (int c = 0; c < 3; c++)
        for (int k = 0; k < 12; k++)
            pack_val(aaxi4_stream_master_0_seq_4.payload, 1 + c*12 + k,
                     real_to_q15((k % 2 == 0) ? 0.083 : -0.083));

    // Samples: 0.6 * sin(2π * (c+1) * 0.07 * n),  n=0..19
    for (int c = 0; c < 3; c++)
        for (int n = 0; n < 20; n++)
            pack_val(aaxi4_stream_master_0_seq_4.payload, 37 + c*20 + n,
                     real_to_q15(0.6 * $sin(2.0 * 3.14159265358979 *
                                            (c+1) * 0.07 * n)));

    aaxi4_stream_master_0_seq_4.start(aaxi4_stream_master_0);
    #10us; // Wait for DUT to flush TV4 output
    // NOTE: No delay needed after the last sequence — the drain_time in
    // top_test_base.svh handles waiting for TV4's DUT output.
endtask: body
